#!/bin/bash
source /etc/lsb-release
KERNEL_RELEASE=$(uname -r)
sed -i "1s/^\([^ ]*\) (\(.*-dotcloud[0-9]\+\).*$/\1 (\2-${KERNEL_RELEASE}~${DISTRIB_CODENAME}) ${DISTRIB_CODENAME}; urgency=low/" changelog
